name = "LocalitySensitive"
uuid = "d5d4b143-b3a8-5f4e-9f7c-34bdd8cea6b0"
authors = ["Alan Schelten <alan.schelten@mercateo.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
