name = "LocalitySensitiveHash"
uuid = "e86dd4bb-4d86-5f4a-bba6-acb318553826"
authors = ["Alan Schelten <alan.schelten@mercateo.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
