name = "LocalitySensitive"
uuid = "d5d4b143-b3a8-5f4e-9f7c-34bdd8cea6b0"
authors = ["Alan Schelten <alan.schelten@mercateo.com>"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
